language: node_js
node_js:
  - "stable"
script:
  - yarn test:cov && codecov
before_install:
  - npm install -g yarn
  - npm i -g codecov
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
