language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run lint
  - yarn run test:cov
before_install:
  - npm install -g yarn
  - npm i -g codecov
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
