language: node_js
node_js:
  - lts/argon
  - lts/boron
  - stable
cache:
  directories:
    - node_modules
before_install:
  - npm install -g yarn
after_success:
  - npm i -g coveralls
  - cat coverage/remapped/lcov.info | coveralls